### ISSUE TITLE
How to translate crop view from center?

### ISSUE THREAD

**Issue by hemangshah** [yuyak/YKImageCropper#1]
Right now I can able to translate crop view from it corners and edges, but I want to something like, I can able to translate crop view if I touch and pan it from the center, it'll go in the direction I am panning? Is this possible?

**Comment by yuyak** [comment]
Hi @hemangshah,
currently, this library doesn't have the feature.
However if you change some codes, it may be possible. I'm not sure about it though.
Thanks.

**Comment by hemangshah** [comment]
@yuyak , Thanks for your comments! I'll check for it. And if possible will fork you for the same :+1:

**Comment by yuyak** [comment]
You're welcome :)
